# Generated by Django 6.1 on 2026-08-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.IntegerField()),
                ('coluna', models.CharField(max_length=255)),
                ('valor', models.TextField()),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='mapa.mapa')),
            ],
        ),
    ]
