services:
  web:
    build: .
    container_name: arsenal
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
