services:
  web:
    build: .
    container_name: arsenal
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: arsenal-db
    environment:
      POSTGRES_DB: arsenal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: arsenal123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: arsenal-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: