# Generated by Django 3.2.12 on 2026-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50)),
                ('data_abertura', models.DateField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
