# Generated by Django 6.1 on 2026-08-18 14:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20260722_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AddField(
            model_name='processo',
            name='arquivo_gerado_odt',
            field=models.FileField(blank=True, null=True, upload_to='processos/gerados/'),
        ),
        migrations.AddField(
            model_name='processo',
            name='arquivo_gerado_xlsx',
            field=models.FileField(blank=True, null=True, upload_to='processos/gerados/'),
        ),
        migrations.AddField(
            model_name='processo',
            name='arquivo_processo',
            field=models.FileField(blank=True, null=True, upload_to='processos/'),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processo',
            name='emails_enviados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processo',
            name='emails_recebidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processo',
            name='qtd_cotacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processo',
            name='qtd_fornecedores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processo',
            name='qtd_fornecedores_com_preco',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processo',
            name='qtd_itens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Em andamento'), ('concluido', 'Concluído'), ('erro', 'Erro no processamento')], default='pendente', max_length=50),
        ),
        migrations.AddField(
            model_name='processo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^([A-Z]{2,4}-)?\\d{4,6}/\\d{4}$', 'Use o formato 00015/2026 ou PE-90043/2026.')]),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('valor_global', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tipo_resposta', models.CharField(choices=[('cotacao', 'Cotação'), ('declinio', 'Declínio'), ('duvida', 'Dúvida/esclarecimento'), ('sem_resposta', 'Sem resposta')], default='cotacao', max_length=20)),
                ('motivo_declinio', models.CharField(blank=True, default='', max_length=255)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='processos.processo')),
            ],
            options={
                'ordering': ['indice'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('pi', models.CharField(blank=True, default='', max_length=50)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('qtde', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('uf', models.CharField(blank=True, default='', max_length=20)),
                ('painel_preco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_unitario_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('confianca', models.PositiveSmallIntegerField(blank=True, help_text='0–100. Abaixo de 80, conferir contra o documento original.', null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='processos.processo')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('texto_original', models.CharField(blank=True, default='', max_length=100)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('confianca', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='processos.fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='processos.item')),
            ],
            options={
                'ordering': ['fornecedor__indice'],
            },
        ),
        migrations.CreateModel(
            name='AvisoProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('atencao', 'Requer conferência'), ('erro', 'Erro')], default='atencao', max_length=10)),
                ('mensagem', models.CharField(max_length=500)),
                ('valor_bruto', models.CharField(blank=True, default='', help_text='Texto original que gerou o aviso.', max_length=200)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='processos.processo')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='processos.fornecedor')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='processos.item')),
            ],
            options={
                'verbose_name': 'Aviso de processamento',
                'verbose_name_plural': 'Avisos de processamento',
                'ordering': ['severidade', 'tipo', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['processo', 'cnpj'], name='forn_processo_cnpj_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('processo', 'indice')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['processo', 'pi'], name='item_processo_pi_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('processo', 'posicao')},
        ),
        migrations.AlterUniqueTogether(
            name='cotacao',
            unique_together={('item', 'fornecedor')},
        ),
        migrations.AddIndex(
            model_name='avisoprocessamento',
            index=models.Index(fields=['processo', 'resolvido'], name='aviso_processo_resolv_idx'),
        ),
    ]
